#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: texfreebazaar
#  pool: 5
#  username: root
#  password: root
#  host: localhost

development:
  adapter: mysql2
  database: texfreebazaar
  username: root
  password: root
  host: localhost