default_env: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: zunest_service
  username: root
  password: root
  host: localhost
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: zunest_service
  username: root
  password: root
  host: localhost
  socket: /tmp/mysql.sock
#
#production: &production
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  pool: 5
#  database: zunest_service
#  username: root
#  password: root
#  host: localhost
#
#test:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  pool: 5
#  database: zunest_service
#  username: root
#  password: root
#  host: localhost